<?php
/**
 * @file
 * image pornographic detect Install file.
 */

/**
 * Implements hook_install().
 */
function image_pornographic_detect_install() {
  $t = get_t();
  variable_set('image_pornographic_detect_active_library', 'php-nudity-detector');
  variable_set('user_picture_pornographic_detect', 1);
  variable_set('image_pornographic_detect_warning_message', $t('The image you uploaded contain pornographic content. You are not allowed to upload pornographic images. Please choose another image.'));
}
/**
 * Implements hook_uninstall().
 */
function image_pornographic_detect_uninstall() {
  /*
   *variable_del('upload_file_types');
   */
  variable_del('user_picture_pornographic_detect');
  variable_del('image_pornographic_detect_active_library');
  variable_del('image_pornographic_detect_warning_message');
}
