<?php

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add the user profile image pornographic restrict setting on the user settings page.
 *
 * @see user_admin_settings()
 */
function image_pornographic_restrict_form_user_admin_settings_alter(&$form, &$form_state) {
  $form['personalization']['pictures']['user_picture_pornographic_restrict'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Pornographic restrict.'),
    '#default_value' => variable_get('user_picture_pornographic_restrict', 0),
  );
}
